[package]
name = "lichess"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2.7.4"
convert_case = { version = "0.8.0", optional = true }
csv = { version = "1.3.1", optional = true }
pgn-reader = "0.26.0"
serde = { version = "1.0.219", features = ["derive"], optional = true }
shakmaty = "0.27.3"
zstd = "0.13.3"

[features]
stats = []
collection = []
full-collection-print = ["collection", "dep:convert_case"]
log = []
csv = ["dep:csv"]
serde = ["csv", "dep:serde"]
