[package]
name = "lichess"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.8.0"
csv = "1.3.1"
memchr = "2.7.4"
pgn-reader = "0.26.0"
serde = { version = "1.0.219", features = ["derive"] }
shakmaty = "0.27.3"
zstd = "0.13.3"
