[package]
name = "lichess"
version = "0.1.0"
edition = "2024"
authors = ["Sílvia Elisabeth Romero García <silviae.romgar@gmail.com>", "Tai Villanueva Saiz"]
description = "A scrapper for files from the Lichess database that generates data for a MySQL database."

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
convert_case = { version = "0.8.0", optional = true }
csv = { version = "1.3.1", optional = true }
memchr = { version = "2.7.4", optional = true }
pgn-reader = "0.26.0"
serde = { version = "1.0.219", features = ["derive"], optional = true }
shakmaty = "0.27.3"
zstd = { version = "0.13.3", optional = true }

[features]
stats = []
check = []
collection = []
full-collection-print = ["collection", "dep:convert_case"]
data = []
clean-data = ["data"]
raw-data = ["data"]
relations = []
log = []
csv = ["dep:csv"]
serde = ["csv", "dep:serde"]
memchr = ["dep:memchr"]
zstd = ["dep:zstd"]

[profile.release]
codegen-units = 1
lto = "fat"
