[package]
name = "lichess"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
convert_case = { version = "0.8.0", optional = true }
csv = { version = "1.3.1", optional = true }
memchr = { version = "2.7.4", optional = true }
pgn-reader = "0.26.0"
serde = { version = "1.0.219", features = ["derive"], optional = true }
shakmaty = "0.27.3"
zstd = { version = "0.13.3", optional = true }

[features]
stats = []
check = []
collection = []
full-collection-print = ["collection", "dep:convert_case"]
data = []
relations = []
log = []
csv = ["dep:csv"]
serde = ["csv", "dep:serde"]
memchr = ["dep:memchr"]
zstd = ["dep:zstd"]
