DROP TABLE IF EXISTS FinalConfiguration;
CREATE TABLE IF NOT EXISTS FinalConfiguration (
FCId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
EndBlackPieces SMALLINT UNSIGNED NOT NULL,
EndWhitePieces SMALLINT UNSIGNED NOT NULL,
EndPawns BIGINT UNSIGNED NOT NULL,
EndKnights BIGINT UNSIGNED NOT NULL,
EndBishops BIGINT UNSIGNED NOT NULL,
EndRooks BIGINT UNSIGNED NOT NULL,
EndQueens BIGINT UNSIGNED NOT NULL,
EndKings BIGINT UNSIGNED NOT NULL,
EndBlack BIGINT UNSIGNED NOT NULL,
EndWhite BIGINT UNSIGNED NOT NULL,
CONSTRAINT UC_FinalConfiguration UNIQUE (EndBlackPieces, EndWhitePieces, EndPawns, EndKnights, EndBishops, EndRooks, EndQueens, EndKings, EndBlack, EndWhite)
);
