DROP TABLE IF EXISTS RuleSet;
CREATE TABLE IF NOT EXISTS RuleSet (
RuleSetId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Name NCHAR(31) NOT NULL,
URLId NCHAR(8) NOT NULL,
Kind ENUM('Arena', 'Swiss', 'Game') NOT NULL,
CONSTRAINT UC_RuleSet UNIQUE (Name, URLId)
);
