DROP TABLE IF EXISTS FinalConfiguration;
CREATE TABLE IF NOT EXISTS FinalConfiguration (
FCId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
EndBlackPieces SMALLINT UNSIGNED NOT NULL,
EndWhitePieces SMALLINT UNSIGNED NOT NULL,
ARow INT UNSIGNED NOT NULL,
BRow INT UNSIGNED NOT NULL,
CRow INT UNSIGNED NOT NULL,
DRow INT UNSIGNED NOT NULL,
ERow INT UNSIGNED NOT NULL,
FRow INT UNSIGNED NOT NULL,
GRow INT UNSIGNED NOT NULL,
HRow INT UNSIGNED NOT NULL,
CONSTRAINT UC_FinalConfiguration UNIQUE (EndBlackPieces, EndWhitePieces, ARow, BRow, CRow, DRow, ERow, FRow, GRow, HRow)
);
