DROP TABLE IF EXISTS Opening;
CREATE TABLE IF NOT EXISTS Opening (
OpeningId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Name NCHAR(100) NOT NULL,
EcoLetter ENUM('Q', 'A', 'B', 'C', 'D', 'E') NOT NULL,
EcoNumber TINYINT(2) UNSIGNED ZEROFILL NOT NULL,
UNIQUE (Name)
);
