DROP TABLE IF EXISTS Move;
CREATE TABLE IF NOT EXISTS Move (
GameId INT NOT NULL,
Num SMALLINT UNSIGNED NOT NULL,
Descriptor INT UNSIGNED NOT NULL,
EvalFloat FLOAT NULL,
EvalInt TINYINT NULL,
Clock TIME NULL,
PRIMARY KEY (GameId, Num),
FOREIGN KEY (GameId) REFERENCES Game(GameId)
);
